### ISSUE TITLE
What?!

### ISSUE THREAD

**Issue by Plasmoner** [Plasmoner/Beyond-my-comprehension#1]
![screenshot_20170717_003300](https://user-images.githubusercontent.com/29124716/28251511-8ac36b20-6a87-11e7-96a0-1f3ded7284e2.png)

![screenshot_20170717_002045](https://user-images.githubusercontent.com/29124716/28251512-9c26a8c8-6a87-11e7-8015-6bbcb9a50640.png)

![screenshot_20170717_002505](https://user-images.githubusercontent.com/29124716/28251516-a796ab72-6a87-11e7-8c77-172cbf51f436.png)

Since I've installed the stuff, where is it? It still looks Plasma to me.

**Comment by Plasmoner** [comment]
More. This is not funny.

![screenshot_20170717_011000](https://user-images.githubusercontent.com/29124716/28251842-9d4a2d90-6a8e-11e7-9251-399100869272.png)
![screenshot_20170717_011121](https://user-images.githubusercontent.com/29124716/28251844-9d4cc726-6a8e-11e7-9914-b20954b1017b.png)
![screenshot_20170717_011203](https://user-images.githubusercontent.com/29124716/28251845-9d4d1cc6-6a8e-11e7-94d4-a60fab9ac868.png)
![screenshot_20170717_011243](https://user-images.githubusercontent.com/29124716/28251846-9d5e31dc-6a8e-11e7-9050-ea64cf462ce9.png)
![screenshot_20170717_011323](https://user-images.githubusercontent.com/29124716/28251847-9d61f09c-6a8e-11e7-8a56-083fef3b7e3b.png)
![screenshot_20170717_011403](https://user-images.githubusercontent.com/29124716/28251848-9d62c79c-6a8e-11e7-9f3c-a79d9d153b60.png)
![screenshot_20170717_011438](https://user-images.githubusercontent.com/29124716/28251849-9d63b292-6a8e-11e7-961b-628116243304.png)
![screenshot_20170717_011456](https://user-images.githubusercontent.com/29124716/28251851-9d66bc08-6a8e-11e7-9d27-a786eb9d27d6.png)
![screenshot_20170717_011518](https://user-images.githubusercontent.com/29124716/28251850-9d660092-6a8e-11e7-98d2-f7e8f4860c70.png)
![screenshot_20170717_011530](https://user-images.githubusercontent.com/29124716/28251852-9d777d68-6a8e-11e7-88a1-7b330469cc98.png)

I have not messed with my Neon installation. Don't have an explanation for it.

@MichaelTunnell What should I understand out of this?

**Comment by Plasmoner** [comment]
Since I've installed the stuff, where is it? It still looks Plasma to me.

**Comment by Plasmoner** [comment]
What's got Cinnamon with Plasma? What the heck is this stuff?

**Comment by Plasmoner** [comment]
The issue has been sorted out on the KDE forum / Neon. This is not an issue one should be surprised by or worried about. It's a non-issue actually. For complete edification, one is recommended to visit the forum.

**Comment by MichaelTunnell** [comment]
> I have not messed with my Neon installation. Don't have an explanation for it.

Screenshots with zero context . . . don't do that.

> This is not an issue one should be surprised by or worried about. It's a non-issue actually.

You didn't describe anything and I am not interested in looking at a batch of screenshots to solve a puzzle.

> For complete edification, one is recommended to visit the forum.

Always this, stop using GitHub like this, please. This is not what GitHub is for.

**Comment by Plasmoner** [comment]
*

**Comment by Plasmoner** [comment]
I take comments from open-minded people.
